"""empty message

Revision ID: c126b1513463
Revises: bf000ec69c16
Create Date: 2022-01-28 18:13:49.861333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c126b1513463'
down_revision = 'bf000ec69c16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'ingredients', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ingredients', type_='unique')
    # ### end Alembic commands ###
