"""empty message

Revision ID: 81746da962e4
Revises: ffdc0a98111c
Create Date: 2022-01-19 15:30:41.149835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81746da962e4'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meal_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meal_plans')
    # ### end Alembic commands ###
